name: Algolia run indexing
on:
    push:
      branches:
        - main
jobs:
    algolia-search:
      runs-on: ubuntu-latest
      env:
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - name: Algolia Jekyll Action
          uses: dieghernan/algolia-jekyll-action@main
          with:
            APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
  